import type { D1Migration } from '@cloudflare/vitest-pool-workers';

import type { Env as WorkerEnv } from './types';

// `cloudflare:test` types its `env` as the global `Cloudflare.Env`, which is
// normally generated by `wrangler types`. Declaring it here keeps the bindings
// in one place — the Worker's own `Env`, plus the migrations the test config
// passes through as a binding because workerd has no filesystem.
declare global {
  namespace Cloudflare {
    interface Env extends WorkerEnv {
      TEST_MIGRATIONS: D1Migration[];
    }
  }
}

export {};
